use csv::ReaderBuilder;
use serde::Deserialize;
use crate::unipept_communicator::get_names_for_taxa;
use crate::http_client::HttpResult;
use std::collections::HashMap;

#[derive(Deserialize)]
struct Row {
    id: String,
    score: String,
    row_type: String,
}

/// Read a CSV-file that was produced by the PepGM algorithm and use it to
/// produce a new CSV-file that only contains the taxon-related information
/// and scores. The string produced by this function can be written directly
/// to a valid CSV-file and contains three columns: `taxon_name`, `taxon_id`,
/// and `score`.
///
/// # Arguments
/// * `csv_content` - A CSV-file (as a string) that has been generated by running the PepGM algorithm.
///
/// # Returns
/// A `String` containing CSV rows with the columns: `taxon_name,taxon_id,score`.
pub async fn clean_csv(csv_content: String) -> HttpResult<String> {
    // Parse CSV input (without headers)
    let mut rdr = ReaderBuilder::new()
        .has_headers(false)
        .from_reader(csv_content.as_bytes());

    let mut tax_ids: Vec<(usize, f32)> = Vec::new();

    for result in rdr.deserialize() {
        let record: Row = result?;
        if record.row_type == "taxon"
            && let (Ok(id), Ok(score)) = (record.id.parse::<usize>(), record.score.parse::<f32>())
        {
            tax_ids.push((id, score));
        }
    }

    // Sort by score ascending
    tax_ids.sort_by(|a, b| a.1.partial_cmp(&b.1).expect("Partial compare returned None"));

    // Collect all taxon IDs for name lookup
    let ids: Vec<usize> = tax_ids.iter().map(|(id, _)| *id).collect();
    let name_mapping: HashMap<usize, String> = get_names_for_taxa(&ids)
        .await
        .map_err(|e| format!("Failed to retrieve taxon names: {e}"))?;

    // Build CSV output
    let mut lines: Vec<String> = Vec::new();
    lines.push("taxon_name,id,score".to_string());

    for (id, score) in tax_ids {
        if let Some(name) = name_mapping.get(&id) {
            lines.push(format!("{name},{id},{score}"));
        }
    }

    Ok(lines.join("\n"))
}


#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_clean_csv_basic() {
        // CSV with two taxa and one non-taxon row
        let csv_input = "1,0.5,taxon\n2,0.2,taxon\n3,0.9,other\n".to_string();

        let result = clean_csv(csv_input).await.unwrap();
        println!("{}", result);
        let expected_lines: Vec<&str> = vec![
            "taxon_name,id,score",
            "Bacteria,2,0.2",
            "root,1,0.5",
        ];
        for line in expected_lines {
            assert!(result.contains(line));
        }
    }

    #[tokio::test]
    async fn test_clean_csv_empty_input() {
        let csv_input = "".to_string();
        let result = clean_csv(csv_input).await;
        assert!(result.is_ok());
        let output = result.unwrap();
        assert!(output.contains("taxon_name,id,score"));
    }
}