name: Build Wheels

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'peptonizer_rust/dist/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86
            runs-on: ubuntu-latest
            python-version: "3.12"
          - name: windows-x86
            runs-on: windows-latest
            python-version: "3.12"
          - name: macos-arm
            runs-on: macos-latest
            python-version: "3.12"
          - name: macos-x86
            runs-on: macos-26-intel
            python-version: "3.12"
          - name: linux-arm
            runs-on: ubuntu-24.04-arm
            python-version: "3.12"

    runs-on: ${{ matrix.runs-on }}

    defaults:
      run:
        working-directory: peptonizer_rust
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: dtolnay/rust-toolchain@stable

      - uses: PyO3/maturin-action@v1
        with:
          command: build
          manylinux: auto
          working-directory: peptonizer_rust
          args: --release --out dist -i python3.12

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.name }}
          path: peptonizer_rust/dist/*.whl

  commit-wheels:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy wheels into repo
        run: |
          mkdir -p peptonizer_rust/dist
          find artifacts -name "*.whl" -exec cp {} peptonizer_rust/dist/ \;

      - name: Commit wheels
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -f peptonizer_rust/dist/*.whl

          git commit -m "Update wheels [skip ci]" || echo "Generate wheel files"

          git push origin HEAD:${GITHUB_REF#refs/heads/}
